demo/src/Entity/Team.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TeamRepository")
 */
class Team
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Company;

    /**
     * @ORM\Column(type="float")
     */
    private $Salary;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->Company;
    }

    public function setCompany(string $Company): self
    {
        $this->Company = $Company;

        return $this;
    }

    public function getSalary(): ?float
    {
        return $this->Salary;
    }

    public function setSalary(float $Salary): self
    {
        $this->Salary = $Salary;

        return $this;
    }
}

demo/src/Form/TeamType.php
<?php

namespace App\Form;

use App\Entity\Team;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TeamType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Name')
            ->add('Company')
            ->add('Salary')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Team::class,
        ]);
    }
}

demo/src/Controller/TeamController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;

use App\Entity\Team;
use App\Form\TeamType;

use App\Repository\TeamRepository;

class TeamController extends AbstractController
{
     /**
     * @Route("/equipe", name="equipe")
     */
    public function team(TeamRepository $repo)
    {
        $team = $repo->findAll();
        return $this->render('team/team.html.twig', [
            "team" => $team
        ]);
    }

    /**
     * @Route("/equipe/new", name="equipe_new")
     * @Route("/equipe/{id}/edit", name="equipe_edit")
     */
    public function gestionTeam(Team $team = null, Request $req, ManagerRegistry $mr){
        if(!$team)
            $team = new Team();
        
        $form = $this->createForm(TeamType::class, $team);
        $form->handleRequest($req);

        if($form->isSubmitted() && $form->isValid()){

            $manager = $mr->getManager();
            $manager->persist($team);
            $manager->flush();

            return $this->redirectToRoute('equipe_show', ['id' => $team->getId()]);      
        }

        return $this->render('team/gestTeam.html.twig',[
            "formTeam" => $form->createView(),
            'editMode' => $team->getId() !== null
        ]);
    }

    /**
     * @Route("/equipe/{id}", name="equipe_show")
     */
    public function team_show(Team $team)
    {
        return $this->render('team/teamShow.html.twig', [
            "team" => $team
        ]);
    }
}

demo/templates/team/team.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h1>Bienvenue dans l'équipe</h1>
<h2>Voici nos champions : </h2>
<section>
    {% for equipier in team %}
        <div>
            <h3> ----- Equipier n°{{ equipier.id }} ----- </h3> 
            <p>Nom : {{ equipier.name }}</p>
            <p>Entreprise : {{ equipier.company }}</p>
            <p>Salaire : {{ equipier.salary }}</p>
            <a href="{{ path('equipe_show', {'id':equipier.id}) }} " class="btn btn-primary">Voir sa fiche</a>
            <br>
        <div>
    {% endfor %}
</section>

{% endblock %}

demo/templates/team/teamShow.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h1>Bienvenue dans l'équipe</h1>
<h2>Voici nos champions : </h2>
<section>
    <div>
        <h3> ----- team n°{{ team.id }} ----- </h3> 
        <p>Nom : {{ team.name }}</p>
        <p>Entreprise : {{ team.company }}</p>
        <p>Salaire : {{ team.salary }}</p>
        <a href="{{ path('equipe_edit' , {'id':team.id}) }}" class="btn btn-primary">Modifier</a>
    <div>
</section>

{% endblock %}